ALTER TABLE items
    ADD COLUMN IF NOT EXISTS chest_width_in DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS shoulder_width_in DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS waist_width_in DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS hip_width_in DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS length_in DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS inseam_in DOUBLE PRECISION;